try:
    f = open('no_name')
except Exception , e:
    print 'error'
    print e